name: dreamaigc

on:
  push:
    branches: [master]

jobs:
  dreamaigc:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.7.0
        with:
          node-version: ${{matrix.node-version}}
      - name: Build Monkey Site
        run: |
          npm install
          npm run build
      - name: Deploy to Github Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: gh-pages
          build_dir: .vitepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



